/// Flutter icons LoginIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LoginIcons
///      fonts:
///       - asset: fonts/LoginIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LoginIcons {
  LoginIcons._();

  static const _kFontFam = 'LoginIcons';

  static const IconData key = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe801, fontFamily: _kFontFam);
}
